# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "http://www.mariozeats.com/"
DefaultContentLanguage  = "en"
title                   = "Mario'z Eats"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = "mariozeats-com"
googleAnalytics         = "G-MGPRB0QBKW"
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/post/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["instagram", "youtube", "reddit", "email"]
  hideEmptyStats        = false
  toc                   = true
  tocWords              = 400

  [params.meta]
    description         = "Website for recipes so I don't forget them"
    author              = ""
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Mario'z Eats"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Mario'z Eats"
    paragraph             = "Neuroscientist. <br>Baker. <br> Follow my progress on IG :3. "
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e35/16584832_298712787211654_1332930382915436544_n.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Mario'z Eats"

  [params.sidebar]
    about               = ""
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "About"
    identifier        = "/about/"
    url               = ""
    pre               = "<i class='fa fa-flask'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "about"
    pre               = "<i class='fas fa-network-wired'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Useful Recipes"
    identifier        = "usefulrecipes"
    url               = "/post/usefulrecipes/"
    pre               = "<i class='fas fa-bread-slice'></i>"
    weight            = 3


[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1
    
[social]
  # Coding Communities
  github                = "pacollins/hugo-future-imperfect-slim"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = "mariozeats"
  quora                 = ""
  youtube               = "channel/UCxBCDttUnqkbX119Py_cPsw"
  vimeo                 = ""
  tiktok                = "mariozeats"
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = "mariozeats"
  tumblr                = ""
  twitter               = ""
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = "mariozeatsdessert@gmail.com"
